language: java
sudo: false

cache:
  directories:
  - $HOME/.m2
  
stages:
  - clean
  - test
  ## require the branch name to be master
  - name: deploy
    if: branch = master

## export GPG details
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

jobs:
  include:
  
  - stage: clean
    name: "Clean workspace"
    script: mvn clean
    
  - stage: test
    name: "Tesing in Java 8"
    jdk: oraclejdk8
    script: mvn clean install -Dmaven.test.skip=true

  - stage: deploy
    name: "Deploy artifact to Maven central"
    jdk: oraclejdk8
    script: mvn clean deploy --settings cd/mvnsettings.xml -P sign,build-extras -Dmaven.test.skip=true
    
