project:
  language: java

pipeline:
  artifact_type: "library"
  stages:
    Build:
      image: "spdc1k8sregistry11.privalia.pin/privalia-qa-worker:0.1.0"
      cmd: "mvn clean install"
      volumes:
        m2-cache: '/home/jenkins/.m2'
    CleanRequirements:
      image: "spdc1k8sregistry11.privalia.pin/privalia-qa-worker:0.1.0"
      cmd: "mvn clean"
      volumes:
        m2-cache: '/home/jenkins/.m2'
