project:
  language: java
pipeline:
  artifact_type: "library"
  stages:
    Build:
      image: "harbor.privalia-test.com/qa/privalia-qa-worker:0.1.0"
      cmd: "mvn clean install"
      volumes:
        m2-cache: '/home/jenkins/.m2'
    CleanRequirements:
      image: "harbor.privalia-test.com/qa/privalia-qa-worker:0.1.0"
      cmd: "mvn clean"
      volumes:
        m2-cache: '/home/jenkins/.m2'
