#####################################################################################
# This is an example configuration file for the gitlab CI pipeline
#
# This template shows how to run the different tests that are provided as an example
# when you first create the project.
#
# Use this template as an starting point for running your own tests on the gitlab
# CI pipeline
#
# Check the README file to see all alternative ways of running your features.
#
# Happy testing!
#####################################################################################


# This template uses jdk11 for for running tests
image: maven:3.6.1-jdk-11

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository


# Use a selenium standalone node for running selenium tests
services:
  - name: selenium/standalone-chrome:3.141.59
    alias: node


# In this example, each runner class is executed in a separate job inside the same stage "test". Jobs that are inside the same stage
# are executed in parallel. This is just an example that you can use as a starting point for executing your tests in the pipeline
# but you can organize your test in any other configuration.
CucumberBackendIT:
  stage: test
  script:
    - 'mvn verify -Dit.test=${groupId}.${artifactId}.${package}.CucumberBackendIT'
  artifacts:
    paths:
    - target/*.json
    when: always
    expire_in: 4 weeks

CucumberRestIT:
  stage: test
  script:
    - 'mvn verify -Dit.test=${groupId}.${artifactId}.${package}.CucumberRestIT'
  artifacts:
    paths:
    - target/*.json
    when: always
    expire_in: 4 weeks

CucumberSeleniumIT:
  stage: test
  script:
    - 'mvn verify -Dit.test=${groupId}.${artifactId}.${package}.CucumberSeleniumIT -DSELENIUM_NODE=node:4444'
  artifacts:
    paths:
    - target/executions/**
    - target/*.json
    when: always
    expire_in: 4 weeks


# This job takes all json files found in target/ to generate an HTML cucumber report which then published
# in Github pages. You need to activate the 'Github pages' functionality in your repo for this to work
pages:
  stage: deploy
  when: always
  script:
    - mvn verify -Dmaven.test.skip=true
    - mkdir -p ./public
    - cp -r target/cucumber-html-reports/* public/
    - cp public/overview-features.html public/index.html
  artifacts:
    paths:
      - public
    expire_in: 4 weeks


