# This workflow will build gingerspec-starter project with Maven

name: gingerspec-starter pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setting up JDK 11
      uses: joschi/setup-jdk@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn install -Dmaven.test.skip=true
